/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FaithfulnessStatusResponse,
  HTTPValidationError,
  ListQueriesQueryListGetParams,
  QueriesResponse,
  QueryCreatedResponse,
  QueryRequest,
  QueryResponse
} from '../../model';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type queryQueryPostResponse200 = {
  data: QueryCreatedResponse
  status: 200
}

export type queryQueryPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type queryQueryPostResponseSuccess = (queryQueryPostResponse200) & {
  headers: Headers;
};
export type queryQueryPostResponseError = (queryQueryPostResponse422) & {
  headers: Headers;
};

export type queryQueryPostResponse = (queryQueryPostResponseSuccess | queryQueryPostResponseError)

export const getQueryQueryPostUrl = () => {




  return `/query`
}

/**
 * Submit a question and receive an explained answer.
 *
 * The response includes:
 * - Generated answer with inline citations [1], [2], etc.
 * - Retrieved chunks with relevance scores
 * - Faithfulness verification (deferred by default: the answer returns
 *   immediately with faithfulness_status "pending"; poll
 *   GET /query/{id}/faithfulness for the report)
 * - Timing trace for the pipeline
 *
 * Rate limited to prevent API abuse (default: 10 requests/minute per IP).
 * @summary Query
 */
export const queryQueryPost = async (queryRequest: QueryRequest, options?: Parameters<typeof customFetch>[1]): Promise<queryQueryPostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<queryQueryPostResponse>(getQueryQueryPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(queryRequest)
  }
);}





export const getQueryQueryPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryQueryPost>>, TError,QueryQueryPostMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof queryQueryPost>>, TError,QueryQueryPostMutationVariables, TContext> => {

const mutationKey = ['queryQueryPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof queryQueryPost>>, QueryQueryPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  queryQueryPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type QueryQueryPostMutationResult = NonNullable<Awaited<ReturnType<typeof queryQueryPost>>>
    export type QueryQueryPostMutationBody = QueryRequest
    export type QueryQueryPostMutationError = HTTPValidationError
    export type QueryQueryPostMutationVariables = {data: QueryRequest}

    /**
 * @summary Query
 */
export const useQueryQueryPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof queryQueryPost>>, TError,QueryQueryPostMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof queryQueryPost>>,
        TError,
        QueryQueryPostMutationVariables,
        TContext
      > => {
      return useMutation(getQueryQueryPostMutationOptions(options), queryClient);
    }
    export type getFaithfulnessQueryQueryIdFaithfulnessGetResponse200 = {
  data: FaithfulnessStatusResponse
  status: 200
}

export type getFaithfulnessQueryQueryIdFaithfulnessGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getFaithfulnessQueryQueryIdFaithfulnessGetResponseSuccess = (getFaithfulnessQueryQueryIdFaithfulnessGetResponse200) & {
  headers: Headers;
};
export type getFaithfulnessQueryQueryIdFaithfulnessGetResponseError = (getFaithfulnessQueryQueryIdFaithfulnessGetResponse422) & {
  headers: Headers;
};

export type getFaithfulnessQueryQueryIdFaithfulnessGetResponse = (getFaithfulnessQueryQueryIdFaithfulnessGetResponseSuccess | getFaithfulnessQueryQueryIdFaithfulnessGetResponseError)

export const getGetFaithfulnessQueryQueryIdFaithfulnessGetUrl = (queryId: string,) => {




  return `/query/${queryId}/faithfulness`
}

/**
 * Poll the faithfulness verification result for a query.
 *
 * Returns status "pending" until the background verification finishes,
 * then "completed" with the full report (or "failed").
 * @summary Get Faithfulness
 */
export const getFaithfulnessQueryQueryIdFaithfulnessGet = async (queryId: string, options?: Parameters<typeof customFetch>[1]): Promise<getFaithfulnessQueryQueryIdFaithfulnessGetResponse> => {

  return customFetch<getFaithfulnessQueryQueryIdFaithfulnessGetResponse>(getGetFaithfulnessQueryQueryIdFaithfulnessGetUrl(queryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFaithfulnessQueryQueryIdFaithfulnessGetQueryKey = (queryId: string,) => {
    return [
    `/query/${queryId}/faithfulness`
    ] as const;
    }


export const getGetFaithfulnessQueryQueryIdFaithfulnessGetQueryOptions = <TData = Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError = HTTPValidationError>(queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFaithfulnessQueryQueryIdFaithfulnessGetQueryKey(queryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>> = ({ signal }) => getFaithfulnessQueryQueryIdFaithfulnessGet(queryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: queryId !== null && queryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFaithfulnessQueryQueryIdFaithfulnessGetQueryResult = NonNullable<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>>
export type GetFaithfulnessQueryQueryIdFaithfulnessGetQueryError = HTTPValidationError


export function useGetFaithfulnessQueryQueryIdFaithfulnessGet<TData = Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError = HTTPValidationError>(
 queryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>,
          TError,
          Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFaithfulnessQueryQueryIdFaithfulnessGet<TData = Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>,
          TError,
          Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFaithfulnessQueryQueryIdFaithfulnessGet<TData = Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Faithfulness
 */

export function useGetFaithfulnessQueryQueryIdFaithfulnessGet<TData = Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFaithfulnessQueryQueryIdFaithfulnessGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFaithfulnessQueryQueryIdFaithfulnessGetQueryOptions(queryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getExplanationQueryQueryIdExplanationGetResponse200 = {
  data: QueryResponse
  status: 200
}

export type getExplanationQueryQueryIdExplanationGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getExplanationQueryQueryIdExplanationGetResponseSuccess = (getExplanationQueryQueryIdExplanationGetResponse200) & {
  headers: Headers;
};
export type getExplanationQueryQueryIdExplanationGetResponseError = (getExplanationQueryQueryIdExplanationGetResponse422) & {
  headers: Headers;
};

export type getExplanationQueryQueryIdExplanationGetResponse = (getExplanationQueryQueryIdExplanationGetResponseSuccess | getExplanationQueryQueryIdExplanationGetResponseError)

export const getGetExplanationQueryQueryIdExplanationGetUrl = (queryId: string,) => {




  return `/query/${queryId}/explanation`
}

/**
 * Retrieve the full explanation for a previous query.
 *
 * Args:
 *     query_id: The UUID returned from POST /query.
 *
 * Returns:
 *     The complete QueryResponse for that query.
 *
 * Raises:
 *     404: If query_id not found.
 * @summary Get Explanation
 */
export const getExplanationQueryQueryIdExplanationGet = async (queryId: string, options?: Parameters<typeof customFetch>[1]): Promise<getExplanationQueryQueryIdExplanationGetResponse> => {

  return customFetch<getExplanationQueryQueryIdExplanationGetResponse>(getGetExplanationQueryQueryIdExplanationGetUrl(queryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExplanationQueryQueryIdExplanationGetQueryKey = (queryId: string,) => {
    return [
    `/query/${queryId}/explanation`
    ] as const;
    }


export const getGetExplanationQueryQueryIdExplanationGetQueryOptions = <TData = Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError = HTTPValidationError>(queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExplanationQueryQueryIdExplanationGetQueryKey(queryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>> = ({ signal }) => getExplanationQueryQueryIdExplanationGet(queryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: queryId !== null && queryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExplanationQueryQueryIdExplanationGetQueryResult = NonNullable<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>>
export type GetExplanationQueryQueryIdExplanationGetQueryError = HTTPValidationError


export function useGetExplanationQueryQueryIdExplanationGet<TData = Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError = HTTPValidationError>(
 queryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>,
          TError,
          Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExplanationQueryQueryIdExplanationGet<TData = Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>,
          TError,
          Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExplanationQueryQueryIdExplanationGet<TData = Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Explanation
 */

export function useGetExplanationQueryQueryIdExplanationGet<TData = Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExplanationQueryQueryIdExplanationGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExplanationQueryQueryIdExplanationGetQueryOptions(queryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listQueriesQueryListGetResponse200 = {
  data: QueriesResponse
  status: 200
}

export type listQueriesQueryListGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type listQueriesQueryListGetResponseSuccess = (listQueriesQueryListGetResponse200) & {
  headers: Headers;
};
export type listQueriesQueryListGetResponseError = (listQueriesQueryListGetResponse422) & {
  headers: Headers;
};

export type listQueriesQueryListGetResponse = (listQueriesQueryListGetResponseSuccess | listQueriesQueryListGetResponseError)

export const getListQueriesQueryListGetUrl = (params?: ListQueriesQueryListGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/query/list?${stringifiedParams}` : `/query/list`
}

/**
 * List recent queries with summary information.
 *
 * Returns:
 *     List of query summaries with id, question, answer preview, and timestamp.
 * @summary List Queries
 */
export const listQueriesQueryListGet = async (params?: ListQueriesQueryListGetParams, options?: Parameters<typeof customFetch>[1]): Promise<listQueriesQueryListGetResponse> => {

  return customFetch<listQueriesQueryListGetResponse>(getListQueriesQueryListGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListQueriesQueryListGetQueryKey = (params?: ListQueriesQueryListGetParams,) => {
    return [
    `/query/list`, ...(params ? [params] : [])
    ] as const;
    }


export const getListQueriesQueryListGetQueryOptions = <TData = Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError = HTTPValidationError>(params?: ListQueriesQueryListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQueriesQueryListGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listQueriesQueryListGet>>> = ({ signal }) => listQueriesQueryListGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListQueriesQueryListGetQueryResult = NonNullable<Awaited<ReturnType<typeof listQueriesQueryListGet>>>
export type ListQueriesQueryListGetQueryError = HTTPValidationError


export function useListQueriesQueryListGet<TData = Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError = HTTPValidationError>(
 params: undefined |  ListQueriesQueryListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQueriesQueryListGet>>,
          TError,
          Awaited<ReturnType<typeof listQueriesQueryListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQueriesQueryListGet<TData = Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError = HTTPValidationError>(
 params?: ListQueriesQueryListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listQueriesQueryListGet>>,
          TError,
          Awaited<ReturnType<typeof listQueriesQueryListGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListQueriesQueryListGet<TData = Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError = HTTPValidationError>(
 params?: ListQueriesQueryListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Queries
 */

export function useListQueriesQueryListGet<TData = Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError = HTTPValidationError>(
 params?: ListQueriesQueryListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listQueriesQueryListGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListQueriesQueryListGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type exportQueryQueryQueryIdExportGetResponse200 = {
  data: unknown
  status: 200
}

export type exportQueryQueryQueryIdExportGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type exportQueryQueryQueryIdExportGetResponseSuccess = (exportQueryQueryQueryIdExportGetResponse200) & {
  headers: Headers;
};
export type exportQueryQueryQueryIdExportGetResponseError = (exportQueryQueryQueryIdExportGetResponse422) & {
  headers: Headers;
};

export type exportQueryQueryQueryIdExportGetResponse = (exportQueryQueryQueryIdExportGetResponseSuccess | exportQueryQueryQueryIdExportGetResponseError)

export const getExportQueryQueryQueryIdExportGetUrl = (queryId: string,) => {




  return `/query/${queryId}/export`
}

/**
 * Export a query as a Markdown file.
 *
 * Args:
 *     query_id: The UUID of the query to export.
 *
 * Returns:
 *     A downloadable Markdown file containing the query details.
 *
 * Raises:
 *     404: If query_id not found.
 * @summary Export Query
 */
export const exportQueryQueryQueryIdExportGet = async (queryId: string, options?: Parameters<typeof customFetch>[1]): Promise<exportQueryQueryQueryIdExportGetResponse> => {

  return customFetch<exportQueryQueryQueryIdExportGetResponse>(getExportQueryQueryQueryIdExportGetUrl(queryId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getExportQueryQueryQueryIdExportGetQueryKey = (queryId: string,) => {
    return [
    `/query/${queryId}/export`
    ] as const;
    }


export const getExportQueryQueryQueryIdExportGetQueryOptions = <TData = Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError = HTTPValidationError>(queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getExportQueryQueryQueryIdExportGetQueryKey(queryId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>> = ({ signal }) => exportQueryQueryQueryIdExportGet(queryId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: queryId !== null && queryId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ExportQueryQueryQueryIdExportGetQueryResult = NonNullable<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>>
export type ExportQueryQueryQueryIdExportGetQueryError = HTTPValidationError


export function useExportQueryQueryQueryIdExportGet<TData = Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError = HTTPValidationError>(
 queryId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportQueryQueryQueryIdExportGet<TData = Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>,
          TError,
          Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useExportQueryQueryQueryIdExportGet<TData = Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Export Query
 */

export function useExportQueryQueryQueryIdExportGet<TData = Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError = HTTPValidationError>(
 queryId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof exportQueryQueryQueryIdExportGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getExportQueryQueryQueryIdExportGetQueryOptions(queryId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






