/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ClustersResponse,
  EmbeddingsResponse
} from '../../model';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get 3D coordinates for all papers.

Returns precomputed UMAP projections and cluster assignments
for visualization. Call POST /admin/papers/recompute-embeddings
to refresh the data.

Returns:
    List of papers with coordinates and cluster assignments.
 * @summary Get Embeddings
 */
export type getEmbeddingsPapersEmbeddingsGetResponse200 = {
  data: EmbeddingsResponse
  status: 200
}

export type getEmbeddingsPapersEmbeddingsGetResponseSuccess = (getEmbeddingsPapersEmbeddingsGetResponse200) & {
  headers: Headers;
};
;

export type getEmbeddingsPapersEmbeddingsGetResponse = (getEmbeddingsPapersEmbeddingsGetResponseSuccess)

export const getGetEmbeddingsPapersEmbeddingsGetUrl = () => {


  

  return `/papers/embeddings`
}

export const getEmbeddingsPapersEmbeddingsGet = async ( options?: RequestInit): Promise<getEmbeddingsPapersEmbeddingsGetResponse> => {
  
  return customFetch<getEmbeddingsPapersEmbeddingsGetResponse>(getGetEmbeddingsPapersEmbeddingsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetEmbeddingsPapersEmbeddingsGetQueryKey = () => {
    return [
    `/papers/embeddings`
    ] as const;
    }

    
export const getGetEmbeddingsPapersEmbeddingsGetQueryOptions = <TData = Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetEmbeddingsPapersEmbeddingsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>> = ({ signal }) => getEmbeddingsPapersEmbeddingsGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetEmbeddingsPapersEmbeddingsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>>
export type GetEmbeddingsPapersEmbeddingsGetQueryError = unknown


export function useGetEmbeddingsPapersEmbeddingsGet<TData = Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>,
          TError,
          Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEmbeddingsPapersEmbeddingsGet<TData = Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>,
          TError,
          Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetEmbeddingsPapersEmbeddingsGet<TData = Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Embeddings
 */

export function useGetEmbeddingsPapersEmbeddingsGet<TData = Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getEmbeddingsPapersEmbeddingsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetEmbeddingsPapersEmbeddingsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get cluster information.

Returns auto-generated clusters with labels based on paper titles.

Returns:
    List of clusters with labels and paper IDs.
 * @summary Get Clusters
 */
export type getClustersPapersClustersGetResponse200 = {
  data: ClustersResponse
  status: 200
}

export type getClustersPapersClustersGetResponseSuccess = (getClustersPapersClustersGetResponse200) & {
  headers: Headers;
};
;

export type getClustersPapersClustersGetResponse = (getClustersPapersClustersGetResponseSuccess)

export const getGetClustersPapersClustersGetUrl = () => {


  

  return `/papers/clusters`
}

export const getClustersPapersClustersGet = async ( options?: RequestInit): Promise<getClustersPapersClustersGetResponse> => {
  
  return customFetch<getClustersPapersClustersGetResponse>(getGetClustersPapersClustersGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetClustersPapersClustersGetQueryKey = () => {
    return [
    `/papers/clusters`
    ] as const;
    }

    
export const getGetClustersPapersClustersGetQueryOptions = <TData = Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClustersPapersClustersGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClustersPapersClustersGet>>> = ({ signal }) => getClustersPapersClustersGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClustersPapersClustersGetQueryResult = NonNullable<Awaited<ReturnType<typeof getClustersPapersClustersGet>>>
export type GetClustersPapersClustersGetQueryError = unknown


export function useGetClustersPapersClustersGet<TData = Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClustersPapersClustersGet>>,
          TError,
          Awaited<ReturnType<typeof getClustersPapersClustersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClustersPapersClustersGet<TData = Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClustersPapersClustersGet>>,
          TError,
          Awaited<ReturnType<typeof getClustersPapersClustersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClustersPapersClustersGet<TData = Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Clusters
 */

export function useGetClustersPapersClustersGet<TData = Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClustersPapersClustersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClustersPapersClustersGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




