/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  LoginRequest,
  LoginResponse,
  UserResponse
} from '../../model';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Authenticate user and set JWT cookie.
 * @summary Login
 */
export type loginAuthLoginPostResponse200 = {
  data: LoginResponse
  status: 200
}

export type loginAuthLoginPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginAuthLoginPostResponseSuccess = (loginAuthLoginPostResponse200) & {
  headers: Headers;
};
export type loginAuthLoginPostResponseError = (loginAuthLoginPostResponse422) & {
  headers: Headers;
};

export type loginAuthLoginPostResponse = (loginAuthLoginPostResponseSuccess | loginAuthLoginPostResponseError)

export const getLoginAuthLoginPostUrl = () => {


  

  return `/auth/login`
}

export const loginAuthLoginPost = async (loginRequest: LoginRequest, options?: RequestInit): Promise<loginAuthLoginPostResponse> => {
  
  return customFetch<loginAuthLoginPostResponse>(getLoginAuthLoginPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}
  



export const getLoginAuthLoginPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginAuthLoginPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginAuthLoginPost>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginAuthLoginPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LoginAuthLoginPostMutationResult = NonNullable<Awaited<ReturnType<typeof loginAuthLoginPost>>>
    export type LoginAuthLoginPostMutationBody = LoginRequest
    export type LoginAuthLoginPostMutationError = HTTPValidationError

    /**
 * @summary Login
 */
export const useLoginAuthLoginPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginAuthLoginPost>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginAuthLoginPost>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {
      return useMutation(getLoginAuthLoginPostMutationOptions(options), queryClient);
    }
    /**
 * Clear the JWT cookie.
 * @summary Logout
 */
export type logoutAuthLogoutPostResponse200 = {
  data: LoginResponse
  status: 200
}

export type logoutAuthLogoutPostResponseSuccess = (logoutAuthLogoutPostResponse200) & {
  headers: Headers;
};
;

export type logoutAuthLogoutPostResponse = (logoutAuthLogoutPostResponseSuccess)

export const getLogoutAuthLogoutPostUrl = () => {


  

  return `/auth/logout`
}

export const logoutAuthLogoutPost = async ( options?: RequestInit): Promise<logoutAuthLogoutPostResponse> => {
  
  return customFetch<logoutAuthLogoutPostResponse>(getLogoutAuthLogoutPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getLogoutAuthLogoutPostMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, TError,void, TContext> => {

const mutationKey = ['logoutAuthLogoutPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, void> = () => {
          

          return  logoutAuthLogoutPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutAuthLogoutPostMutationResult = NonNullable<Awaited<ReturnType<typeof logoutAuthLogoutPost>>>
    
    export type LogoutAuthLogoutPostMutationError = unknown

    /**
 * @summary Logout
 */
export const useLogoutAuthLogoutPost = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutAuthLogoutPost>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutAuthLogoutPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutAuthLogoutPostMutationOptions(options), queryClient);
    }
    /**
 * Get the current authenticated user.
 * @summary Get Current User
 */
export type getCurrentUserAuthMeGetResponse200 = {
  data: UserResponse
  status: 200
}

export type getCurrentUserAuthMeGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getCurrentUserAuthMeGetResponseSuccess = (getCurrentUserAuthMeGetResponse200) & {
  headers: Headers;
};
export type getCurrentUserAuthMeGetResponseError = (getCurrentUserAuthMeGetResponse422) & {
  headers: Headers;
};

export type getCurrentUserAuthMeGetResponse = (getCurrentUserAuthMeGetResponseSuccess | getCurrentUserAuthMeGetResponseError)

export const getGetCurrentUserAuthMeGetUrl = () => {


  

  return `/auth/me`
}

export const getCurrentUserAuthMeGet = async ( options?: RequestInit): Promise<getCurrentUserAuthMeGetResponse> => {
  
  return customFetch<getCurrentUserAuthMeGetResponse>(getGetCurrentUserAuthMeGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetCurrentUserAuthMeGetQueryKey = () => {
    return [
    `/auth/me`
    ] as const;
    }

    
export const getGetCurrentUserAuthMeGetQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentUserAuthMeGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>> = ({ signal }) => getCurrentUserAuthMeGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentUserAuthMeGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>>
export type GetCurrentUserAuthMeGetQueryError = HTTPValidationError


export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>,
          TError,
          Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Current User
 */

export function useGetCurrentUserAuthMeGet<TData = Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentUserAuthMeGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentUserAuthMeGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




