/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Maps a claim in the answer to source chunks.
 */
export interface Citation {
  /** The specific claim/sentence in the answer */
  claim: string;
  /** Source chunk IDs supporting this claim */
  chunk_ids: string[];
  /**
     * Confidence score
     * @minimum 0
     * @maximum 1
     */
  confidence: number;
}
