/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Verification result for a single claim.
 */
export interface ClaimVerification {
  /** The extracted claim from the answer */
  claim: string;
  /** 'supported' | 'unsupported' | 'partial' */
  verdict: string;
  /** Chunk IDs that support/refute this claim */
  evidence_chunk_ids: string[];
  /** LLM's explanation for the verdict */
  reasoning: string;
}
