/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Cluster information.
 */
export interface ClusterInfo {
  id: number;
  label: string;
  paper_ids: string[];
}
