/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { ClusterInfo } from './clusterInfo';

/**
 * Response model for clusters.
 */
export interface ClustersResponse {
  clusters: ClusterInfo[];
  /** ISO timestamp of last computation */
  computed_at: string | null;
}
