/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { PaperWithCoordinates } from './paperWithCoordinates';

/**
 * Response model for paper embeddings/coordinates.
 */
export interface EmbeddingsResponse {
  papers: PaperWithCoordinates[];
  /** ISO timestamp of last computation */
  computed_at: string | null;
}
