/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional request body for evaluation with ground truth.
 */
export interface EvaluateRequest {
  ground_truth?: string | null;
}
