/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { EvaluationMetrics } from './evaluationMetrics';

/**
 * Complete evaluation result for a query.
 */
export interface EvaluationResult {
  query_id: string;
  metrics: EvaluationMetrics;
  evaluated_at: string;
  evaluation_time_ms: number;
}
