/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * RAGAS evaluation metrics for a RAG response.
 */
export interface EvaluationMetrics {
  /**
     * Factual consistency of answer against context
     * @minimum 0
     * @maximum 1
     */
  faithfulness: number;
  /**
     * Relevance of answer to the question
     * @minimum 0
     * @maximum 1
     */
  answer_relevancy: number;
  /**
     * Precision of retrieved context
     * @minimum 0
     * @maximum 1
     */
  context_precision: number;
  /**
     * Recall of retrieved context (requires ground truth)
     * @minimum 0
     * @maximum 1
     */
  context_recall: number;
}
