/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Timing breakdown for the query pipeline.
 */
export interface ExplanationTrace {
  /** Time to embed query */
  embedding_time_ms: number;
  /** Time to search vector store */
  retrieval_time_ms: number;
  /** Time for reranking (if enabled) */
  reranking_time_ms?: number | null;
  /** Time for LLM generation */
  generation_time_ms: number;
  /** Time for faithfulness verification (None while pending) */
  faithfulness_time_ms?: number | null;
  /** Total pipeline time */
  total_time_ms: number;
}
