/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { FaithfulnessResult } from './faithfulnessResult';

/**
 * Polling response for deferred faithfulness verification.
 */
export interface FaithfulnessStatusResponse {
  query_id: string;
  /** completed | pending | failed */
  status: string;
  /** The report once verification completed */
  faithfulness?: FaithfulnessResult | null;
  /** Verification duration once completed */
  faithfulness_time_ms?: number | null;
}
