/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { ClaimVerification } from './claimVerification';

/**
 * Overall faithfulness assessment of an answer.
 */
export interface FaithfulnessResult {
  /**
     * Overall faithfulness score
     * @minimum 0
     * @maximum 1
     */
  score: number;
  /** Per-claim verification results */
  claims: ClaimVerification[];
}
