/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response model for health check.
 */
export interface HealthResponse {
  status: string;
  papers_count: number;
  chunks_count: number;
}
