/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request model for paper ingestion.
 */
export interface IngestRequest {
  /** List of arXiv IDs to ingest */
  arxiv_ids?: string[] | null;
  /** Search query to find papers to ingest */
  search_query?: string | null;
  /**
   * Max papers to ingest from search
   * @minimum 1
   * @maximum 20
   */
  max_results?: number;
}
