/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Result for a single paper ingestion.
 */
export interface IngestResultItem {
  arxiv_id: string;
  title: string;
  chunk_count: number;
  status: string;
  error?: string | null;
}
