/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { IngestResultItem } from './ingestResultItem';

/**
 * Response model for paper ingestion.
 */
export interface IngestResponse {
  ingested: IngestResultItem[];
  errors: IngestResultItem[];
}
