/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

export type ListQueriesQueryListGetParams = {
/**
 * Max number of queries to return
 * @minimum 1
 * @maximum 100
 */
limit?: number;
};
