/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Paper search result for preview before ingestion.
 */
export interface PaperSearchResult {
  arxiv_id: string;
  title: string;
  authors: string[];
  abstract: string;
  url: string;
}
