/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { PaperInfo } from './paperInfo';

/**
 * Response model for listing papers.
 */
export interface PapersResponse {
  papers: PaperInfo[];
  total: number;
}
