/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Paper with 3D coordinates for visualization.
 */
export interface PaperWithCoordinates {
  paper_id: string;
  arxiv_id: string;
  title: string;
  /**
     * [x, y, z] UMAP coordinates
     * @minItems 3
     * @maxItems 3
     */
  coords: [number, number, number];
  /** Cluster assignment (None for noise) */
  cluster_id: number | null;
  chunk_count: number;
}
