/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Information about an ingested paper.
 */
export interface PaperInfo {
  paper_id: string;
  arxiv_id: string;
  title: string;
  chunk_count: number;
}
