/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { PaperSearchResult } from './paperSearchResult';

/**
 * Response model for paper search.
 */
export interface PaperSearchResponse {
  papers: PaperSearchResult[];
  total: number;
}
