/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Verification lifecycle; 'pending' when verification runs after the answer
 */
export type QueryCreatedResponseFaithfulnessStatus = typeof QueryCreatedResponseFaithfulnessStatus[keyof typeof QueryCreatedResponseFaithfulnessStatus];


export const QueryCreatedResponseFaithfulnessStatus = {
  completed: 'completed',
  pending: 'pending',
  failed: 'failed',
} as const;
