/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Summary of a stored query.
 */
export interface QuerySummary {
  query_id: string;
  question: string;
  answer_preview: string;
  created_at: string;
}
