/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request model for query endpoint.
 *
 * The bounds are not cosmetic: every question is embedded, sent to the LLM,
 * and persisted, so an unbounded field is a cost-amplification vector on an
 * endpoint anyone can reach.
 */
export interface QueryRequest {
  /**
     * Natural language question
     * @minLength 1
     * @maxLength 2000
     */
  question: string;
  /**
     * Number of chunks to retrieve
     * @minimum 1
     * @maximum 50
     */
  top_k?: number;
  /** Optional: scope query to specific papers */
  paper_ids?: string[] | null;
  /** Enable cross-encoder reranking */
  enable_reranking?: boolean;
}
