/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { QuerySummary } from './querySummary';

/**
 * Response model for listing recent queries.
 */
export interface QueriesResponse {
  queries: QuerySummary[];
  total: number;
}
