/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request model for query endpoint.
 */
export interface QueryRequest {
  /** Natural language question */
  question: string;
  /**
     * Number of chunks to retrieve
     * @minimum 1
     * @maximum 50
     */
  top_k?: number;
  /** Optional: scope query to specific papers */
  paper_ids?: string[] | null;
  /** Enable cross-encoder reranking */
  enable_reranking?: boolean;
}
