/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Verification lifecycle; 'pending' when verification runs after the answer
 */
export type QueryResponseFaithfulnessStatus = typeof QueryResponseFaithfulnessStatus[keyof typeof QueryResponseFaithfulnessStatus];


export const QueryResponseFaithfulnessStatus = {
  completed: 'completed',
  pending: 'pending',
  failed: 'failed',
} as const;
