/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { Citation } from './citation';
import type { ExplanationTrace } from './explanationTrace';
import type { FaithfulnessResult } from './faithfulnessResult';
import type { QueryCreatedResponseFaithfulnessStatus } from './queryCreatedResponseFaithfulnessStatus';
import type { RetrievedChunk } from './retrievedChunk';

/**
 * A fresh query result plus the capability to read it again.
 *
 * share_token is a transport concern, so it lives here rather than on the
 * QueryResponse entity: the domain does not know about HTTP authorization.
 */
export interface QueryCreatedResponse {
  /** UUID for retrieving explanation later */
  query_id: string;
  /** Original question */
  question: string;
  /** Generated answer with inline citations */
  answer: string;
  /** Citation mappings */
  citations: Citation[];
  /** Retrieved chunks with scores */
  retrieved_chunks: RetrievedChunk[];
  /** Faithfulness verification result (None while verification is pending) */
  faithfulness?: FaithfulnessResult | null;
  /** Verification lifecycle; 'pending' when verification runs after the answer */
  faithfulness_status?: QueryCreatedResponseFaithfulnessStatus;
  /** Timing breakdown */
  trace: ExplanationTrace;
  /** Short-lived token authorizing reads of this query's explanation and export */
  share_token: string;
}
