/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import type { Citation } from './citation';
import type { ExplanationTrace } from './explanationTrace';
import type { FaithfulnessResult } from './faithfulnessResult';
import type { RetrievedChunk } from './retrievedChunk';

/**
 * Complete response for a query including all explainability data.
 */
export interface QueryResponse {
  /** UUID for retrieving explanation later */
  query_id: string;
  /** Original question */
  question: string;
  /** Generated answer with inline citations */
  answer: string;
  /** Citation mappings */
  citations: Citation[];
  /** Retrieved chunks with scores */
  retrieved_chunks: RetrievedChunk[];
  /** Faithfulness verification result */
  faithfulness: FaithfulnessResult;
  /** Timing breakdown */
  trace: ExplanationTrace;
}
