/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response model for recompute operation.
 */
export interface RecomputeResponse {
  papers_processed: number;
  clusters_found: number;
  time_ms: number;
}
