/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * A chunk retrieved from the vector store with scoring metadata.
 */
export interface RetrievedChunk {
  /** Chunk UUID */
  chunk_id: string;
  /** Parent paper UUID */
  paper_id: string;
  /** Title of the source paper */
  paper_title: string;
  /** Chunk text content */
  content: string;
  /** Cosine similarity score */
  similarity_score: number;
  /** Cross-encoder score if reranking enabled */
  rerank_score?: number | null;
  /** Rank before reranking (1-indexed), same as rank if reranking disabled */
  original_rank: number;
  /** Final rank after retrieval/reranking (1-indexed) */
  rank: number;
}
