/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

export type SearchPapersPapersSearchGetParams = {
/**
 * Search query for arXiv
 * @minLength 2
 */
query: string;
/**
 * Maximum results
 * @minimum 1
 * @maximum 20
 */
max_results?: number;
};
