/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response model for system statistics.
 */
export interface SystemStats {
  papers_count: number;
  chunks_count: number;
  queries_count: number;
  backend_status?: string;
}
