/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  IngestRequest,
  IngestResponse
} from '../../model';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type ingestPapersIngestPostResponse200 = {
  data: IngestResponse
  status: 200
}

export type ingestPapersIngestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type ingestPapersIngestPostResponseSuccess = (ingestPapersIngestPostResponse200) & {
  headers: Headers;
};
export type ingestPapersIngestPostResponseError = (ingestPapersIngestPostResponse422) & {
  headers: Headers;
};

export type ingestPapersIngestPostResponse = (ingestPapersIngestPostResponseSuccess | ingestPapersIngestPostResponseError)

export const getIngestPapersIngestPostUrl = () => {




  return `/ingest`
}

/**
 * Ingest papers from arXiv.
 *
 * Provide either `arxiv_ids` for specific papers, or `search_query`
 * to search and ingest papers. If both are provided, `arxiv_ids` takes precedence.
 * @summary Ingest Papers
 */
export const ingestPapersIngestPost = async (ingestRequest: IngestRequest, options?: Parameters<typeof customFetch>[1]): Promise<ingestPapersIngestPostResponse> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Array.isArray(h)) return Object.fromEntries(h);
    return h;
  };
return customFetch<ingestPapersIngestPostResponse>(getIngestPapersIngestPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(ingestRequest)
  }
);}





export const getIngestPapersIngestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestPapersIngestPost>>, TError,IngestPapersIngestPostMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof ingestPapersIngestPost>>, TError,IngestPapersIngestPostMutationVariables, TContext> => {

const mutationKey = ['ingestPapersIngestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ingestPapersIngestPost>>, IngestPapersIngestPostMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  ingestPapersIngestPost(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type IngestPapersIngestPostMutationResult = NonNullable<Awaited<ReturnType<typeof ingestPapersIngestPost>>>
    export type IngestPapersIngestPostMutationBody = IngestRequest
    export type IngestPapersIngestPostMutationError = HTTPValidationError
    export type IngestPapersIngestPostMutationVariables = {data: IngestRequest}

    /**
 * @summary Ingest Papers
 */
export const useIngestPapersIngestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestPapersIngestPost>>, TError,IngestPapersIngestPostMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ingestPapersIngestPost>>,
        TError,
        IngestPapersIngestPostMutationVariables,
        TContext
      > => {
      return useMutation(getIngestPapersIngestPostMutationOptions(options), queryClient);
    }
