/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  IngestRequest,
  IngestResponse
} from '../../model';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Ingest papers from arXiv.

Provide either `arxiv_ids` for specific papers, or `search_query`
to search and ingest papers. If both are provided, `arxiv_ids` takes precedence.
 * @summary Ingest Papers
 */
export type ingestPapersIngestPostResponse200 = {
  data: IngestResponse
  status: 200
}

export type ingestPapersIngestPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type ingestPapersIngestPostResponseSuccess = (ingestPapersIngestPostResponse200) & {
  headers: Headers;
};
export type ingestPapersIngestPostResponseError = (ingestPapersIngestPostResponse422) & {
  headers: Headers;
};

export type ingestPapersIngestPostResponse = (ingestPapersIngestPostResponseSuccess | ingestPapersIngestPostResponseError)

export const getIngestPapersIngestPostUrl = () => {


  

  return `/ingest`
}

export const ingestPapersIngestPost = async (ingestRequest: IngestRequest, options?: RequestInit): Promise<ingestPapersIngestPostResponse> => {
  
  return customFetch<ingestPapersIngestPostResponse>(getIngestPapersIngestPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      ingestRequest,)
  }
);}
  



export const getIngestPapersIngestPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestPapersIngestPost>>, TError,{data: IngestRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof ingestPapersIngestPost>>, TError,{data: IngestRequest}, TContext> => {

const mutationKey = ['ingestPapersIngestPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof ingestPapersIngestPost>>, {data: IngestRequest}> = (props) => {
          const {data} = props ?? {};

          return  ingestPapersIngestPost(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type IngestPapersIngestPostMutationResult = NonNullable<Awaited<ReturnType<typeof ingestPapersIngestPost>>>
    export type IngestPapersIngestPostMutationBody = IngestRequest
    export type IngestPapersIngestPostMutationError = HTTPValidationError

    /**
 * @summary Ingest Papers
 */
export const useIngestPapersIngestPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof ingestPapersIngestPost>>, TError,{data: IngestRequest}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof ingestPapersIngestPost>>,
        TError,
        {data: IngestRequest},
        TContext
      > => {
      return useMutation(getIngestPapersIngestPostMutationOptions(options), queryClient);
    }
    