/**
 * Generated by orval 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeletePaperResponse,
  HTTPValidationError,
  PaperSearchResponse,
  PapersResponse,
  SearchPapersPapersSearchGetParams
} from '../../model';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listPapersPapersGetResponse200 = {
  data: PapersResponse
  status: 200
}

export type listPapersPapersGetResponseSuccess = (listPapersPapersGetResponse200) & {
  headers: Headers;
};
;

export type listPapersPapersGetResponse = (listPapersPapersGetResponseSuccess)

export const getListPapersPapersGetUrl = () => {




  return `/papers`
}

/**
 * List all ingested papers.
 * @summary List Papers
 */
export const listPapersPapersGet = async ( options?: Parameters<typeof customFetch>[1]): Promise<listPapersPapersGetResponse> => {

  return customFetch<listPapersPapersGetResponse>(getListPapersPapersGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListPapersPapersGetQueryKey = () => {
    return [
    `/papers`
    ] as const;
    }


export const getListPapersPapersGetQueryOptions = <TData = Awaited<ReturnType<typeof listPapersPapersGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPapersPapersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListPapersPapersGetQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listPapersPapersGet>>> = ({ signal }) => listPapersPapersGet({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listPapersPapersGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListPapersPapersGetQueryResult = NonNullable<Awaited<ReturnType<typeof listPapersPapersGet>>>
export type ListPapersPapersGetQueryError = unknown


export function useListPapersPapersGet<TData = Awaited<ReturnType<typeof listPapersPapersGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPapersPapersGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPapersPapersGet>>,
          TError,
          Awaited<ReturnType<typeof listPapersPapersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPapersPapersGet<TData = Awaited<ReturnType<typeof listPapersPapersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPapersPapersGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listPapersPapersGet>>,
          TError,
          Awaited<ReturnType<typeof listPapersPapersGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListPapersPapersGet<TData = Awaited<ReturnType<typeof listPapersPapersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPapersPapersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Papers
 */

export function useListPapersPapersGet<TData = Awaited<ReturnType<typeof listPapersPapersGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listPapersPapersGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListPapersPapersGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type deletePaperPapersPaperIdDeleteResponse200 = {
  data: DeletePaperResponse
  status: 200
}

export type deletePaperPapersPaperIdDeleteResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type deletePaperPapersPaperIdDeleteResponseSuccess = (deletePaperPapersPaperIdDeleteResponse200) & {
  headers: Headers;
};
export type deletePaperPapersPaperIdDeleteResponseError = (deletePaperPapersPaperIdDeleteResponse422) & {
  headers: Headers;
};

export type deletePaperPapersPaperIdDeleteResponse = (deletePaperPapersPaperIdDeleteResponseSuccess | deletePaperPapersPaperIdDeleteResponseError)

export const getDeletePaperPapersPaperIdDeleteUrl = (paperId: string,) => {




  return `/papers/${paperId}`
}

/**
 * Delete a paper and all its chunks.
 *
 * Args:
 *     paper_id: The paper ID to delete.
 *
 * Returns:
 *     Deletion result with count of deleted chunks.
 *
 * Raises:
 *     HTTPException: 404 if paper not found.
 * @summary Delete Paper
 */
export const deletePaperPapersPaperIdDelete = async (paperId: string, options?: Parameters<typeof customFetch>[1]): Promise<deletePaperPapersPaperIdDeleteResponse> => {

  return customFetch<deletePaperPapersPaperIdDeleteResponse>(getDeletePaperPapersPaperIdDeleteUrl(paperId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeletePaperPapersPaperIdDeleteMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePaperPapersPaperIdDelete>>, TError,DeletePaperPapersPaperIdDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deletePaperPapersPaperIdDelete>>, TError,DeletePaperPapersPaperIdDeleteMutationVariables, TContext> => {

const mutationKey = ['deletePaperPapersPaperIdDelete'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deletePaperPapersPaperIdDelete>>, DeletePaperPapersPaperIdDeleteMutationVariables> = (props) => {
          const {paperId} = props ?? {};

          return  deletePaperPapersPaperIdDelete(paperId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeletePaperPapersPaperIdDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deletePaperPapersPaperIdDelete>>>

    export type DeletePaperPapersPaperIdDeleteMutationError = HTTPValidationError
    export type DeletePaperPapersPaperIdDeleteMutationVariables = {paperId: string}

    /**
 * @summary Delete Paper
 */
export const useDeletePaperPapersPaperIdDelete = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deletePaperPapersPaperIdDelete>>, TError,DeletePaperPapersPaperIdDeleteMutationVariables, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deletePaperPapersPaperIdDelete>>,
        TError,
        DeletePaperPapersPaperIdDeleteMutationVariables,
        TContext
      > => {
      return useMutation(getDeletePaperPapersPaperIdDeleteMutationOptions(options), queryClient);
    }
    export type searchPapersPapersSearchGetResponse200 = {
  data: PaperSearchResponse
  status: 200
}

export type searchPapersPapersSearchGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type searchPapersPapersSearchGetResponseSuccess = (searchPapersPapersSearchGetResponse200) & {
  headers: Headers;
};
export type searchPapersPapersSearchGetResponseError = (searchPapersPapersSearchGetResponse422) & {
  headers: Headers;
};

export type searchPapersPapersSearchGetResponse = (searchPapersPapersSearchGetResponseSuccess | searchPapersPapersSearchGetResponseError)

export const getSearchPapersPapersSearchGetUrl = (params: SearchPapersPapersSearchGetParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/papers/search?${stringifiedParams}` : `/papers/search`
}

/**
 * Search arXiv for papers without ingesting them.
 *
 * This endpoint allows admins to search arXiv and preview results
 * before deciding which papers to ingest.
 *
 * Args:
 *     query: Search query string (min 2 characters).
 *     max_results: Maximum number of results to return (1-20).
 *
 * Returns:
 *     List of matching papers with metadata.
 *
 * Raises:
 *     502: If the arXiv search fails.
 *     503: If paper source is not configured.
 * @summary Search Papers
 */
export const searchPapersPapersSearchGet = async (params: SearchPapersPapersSearchGetParams, options?: Parameters<typeof customFetch>[1]): Promise<searchPapersPapersSearchGetResponse> => {

  return customFetch<searchPapersPapersSearchGetResponse>(getSearchPapersPapersSearchGetUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSearchPapersPapersSearchGetQueryKey = (params?: SearchPapersPapersSearchGetParams,) => {
    return [
    `/papers/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchPapersPapersSearchGetQueryOptions = <TData = Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError = HTTPValidationError>(params: SearchPapersPapersSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchPapersPapersSearchGetQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>> = ({ signal }) => searchPapersPapersSearchGet(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchPapersPapersSearchGetQueryResult = NonNullable<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>>
export type SearchPapersPapersSearchGetQueryError = HTTPValidationError


export function useSearchPapersPapersSearchGet<TData = Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError = HTTPValidationError>(
 params: SearchPapersPapersSearchGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPapersPapersSearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchPapersPapersSearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPapersPapersSearchGet<TData = Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError = HTTPValidationError>(
 params: SearchPapersPapersSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchPapersPapersSearchGet>>,
          TError,
          Awaited<ReturnType<typeof searchPapersPapersSearchGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchPapersPapersSearchGet<TData = Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError = HTTPValidationError>(
 params: SearchPapersPapersSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Search Papers
 */

export function useSearchPapersPapersSearchGet<TData = Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError = HTTPValidationError>(
 params: SearchPapersPapersSearchGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchPapersPapersSearchGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchPapersPapersSearchGetQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






