/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * ExplainRAG
 * Explainable Retrieval-Augmented Generation for academic papers
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EvaluateRequest,
  EvaluationResult,
  HTTPValidationError,
  RecomputeResponse,
  SystemStats
} from '../../model';

import { customFetch } from '../../custom-fetch';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Trigger recomputation of embedding coordinates and clusters.

This operation:
1. Retrieves all paper embeddings from the vector store
2. Runs UMAP dimensionality reduction to project to 3D
3. Runs HDBSCAN clustering to group similar papers
4. Generates cluster labels from paper titles

The results are cached in memory until the next recompute.

Returns:
    Statistics about the recomputation.

Raises:
    HTTPException: 500 if recomputation fails.
 * @summary Recompute Embeddings
 */
export type recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponse200 = {
  data: RecomputeResponse
  status: 200
}

export type recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponseSuccess = (recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponse200) & {
  headers: Headers;
};
export type recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponseError = (recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponse422) & {
  headers: Headers;
};

export type recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponse = (recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponseSuccess | recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponseError)

export const getRecomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostUrl = () => {


  

  return `/admin/papers/recompute-embeddings`
}

export const recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost = async ( options?: RequestInit): Promise<recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponse> => {
  
  return customFetch<recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostResponse>(getRecomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
  



export const getRecomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost>>, TError,void, TContext> => {

const mutationKey = ['recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost>>, void> = () => {
          

          return  recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost(requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RecomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostMutationResult = NonNullable<Awaited<ReturnType<typeof recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost>>>
    
    export type RecomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostMutationError = HTTPValidationError

    /**
 * @summary Recompute Embeddings
 */
export const useRecomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof recomputeEmbeddingsAdminPapersRecomputeEmbeddingsPost>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRecomputeEmbeddingsAdminPapersRecomputeEmbeddingsPostMutationOptions(options), queryClient);
    }
    /**
 * Get system statistics for admin dashboard.
 * @summary Get Stats
 */
export type getStatsStatsGetResponse200 = {
  data: SystemStats
  status: 200
}

export type getStatsStatsGetResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type getStatsStatsGetResponseSuccess = (getStatsStatsGetResponse200) & {
  headers: Headers;
};
export type getStatsStatsGetResponseError = (getStatsStatsGetResponse422) & {
  headers: Headers;
};

export type getStatsStatsGetResponse = (getStatsStatsGetResponseSuccess | getStatsStatsGetResponseError)

export const getGetStatsStatsGetUrl = () => {


  

  return `/stats`
}

export const getStatsStatsGet = async ( options?: RequestInit): Promise<getStatsStatsGetResponse> => {
  
  return customFetch<getStatsStatsGetResponse>(getGetStatsStatsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}
  




export const getGetStatsStatsGetQueryKey = () => {
    return [
    `/stats`
    ] as const;
    }

    
export const getGetStatsStatsGetQueryOptions = <TData = Awaited<ReturnType<typeof getStatsStatsGet>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatsStatsGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatsStatsGet>>> = ({ signal }) => getStatsStatsGet({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatsStatsGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatsStatsGetQueryResult = NonNullable<Awaited<ReturnType<typeof getStatsStatsGet>>>
export type GetStatsStatsGetQueryError = HTTPValidationError


export function useGetStatsStatsGet<TData = Awaited<ReturnType<typeof getStatsStatsGet>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsStatsGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatsStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getStatsStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatsStatsGet<TData = Awaited<ReturnType<typeof getStatsStatsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsStatsGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatsStatsGet>>,
          TError,
          Awaited<ReturnType<typeof getStatsStatsGet>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatsStatsGet<TData = Awaited<ReturnType<typeof getStatsStatsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Stats
 */

export function useGetStatsStatsGet<TData = Awaited<ReturnType<typeof getStatsStatsGet>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatsStatsGet>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatsStatsGetQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Evaluate a stored query using RAGAS metrics.

This endpoint retrieves a previously stored query and runs RAGAS
evaluation to compute:
- Faithfulness: How factually consistent is the answer with the context
- Answer Relevancy: How relevant is the answer to the question
- Context Precision: How precise is the retrieved context
- Context Recall: How well the context covers the answer (requires ground_truth)

Args:
    query_id: The UUID of the stored query to evaluate.
    request: Optional body with ground_truth for context_recall metric.

Returns:
    EvaluationResult with all computed metrics.

Raises:
    404: If query not found.
    500: If evaluation fails.
 * @summary Evaluate Query
 */
export type evaluateQueryEvaluationQueryQueryIdPostResponse200 = {
  data: EvaluationResult
  status: 200
}

export type evaluateQueryEvaluationQueryQueryIdPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type evaluateQueryEvaluationQueryQueryIdPostResponseSuccess = (evaluateQueryEvaluationQueryQueryIdPostResponse200) & {
  headers: Headers;
};
export type evaluateQueryEvaluationQueryQueryIdPostResponseError = (evaluateQueryEvaluationQueryQueryIdPostResponse422) & {
  headers: Headers;
};

export type evaluateQueryEvaluationQueryQueryIdPostResponse = (evaluateQueryEvaluationQueryQueryIdPostResponseSuccess | evaluateQueryEvaluationQueryQueryIdPostResponseError)

export const getEvaluateQueryEvaluationQueryQueryIdPostUrl = (queryId: string,) => {


  

  return `/evaluation/query/${queryId}`
}

export const evaluateQueryEvaluationQueryQueryIdPost = async (queryId: string,
    evaluateRequestNull: EvaluateRequest | null, options?: RequestInit): Promise<evaluateQueryEvaluationQueryQueryIdPostResponse> => {
  
  return customFetch<evaluateQueryEvaluationQueryQueryIdPostResponse>(getEvaluateQueryEvaluationQueryQueryIdPostUrl(queryId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      evaluateRequestNull,)
  }
);}
  



export const getEvaluateQueryEvaluationQueryQueryIdPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof evaluateQueryEvaluationQueryQueryIdPost>>, TError,{queryId: string;data: EvaluateRequest | null}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof evaluateQueryEvaluationQueryQueryIdPost>>, TError,{queryId: string;data: EvaluateRequest | null}, TContext> => {

const mutationKey = ['evaluateQueryEvaluationQueryQueryIdPost'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof evaluateQueryEvaluationQueryQueryIdPost>>, {queryId: string;data: EvaluateRequest | null}> = (props) => {
          const {queryId,data} = props ?? {};

          return  evaluateQueryEvaluationQueryQueryIdPost(queryId,data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EvaluateQueryEvaluationQueryQueryIdPostMutationResult = NonNullable<Awaited<ReturnType<typeof evaluateQueryEvaluationQueryQueryIdPost>>>
    export type EvaluateQueryEvaluationQueryQueryIdPostMutationBody = EvaluateRequest | null
    export type EvaluateQueryEvaluationQueryQueryIdPostMutationError = HTTPValidationError

    /**
 * @summary Evaluate Query
 */
export const useEvaluateQueryEvaluationQueryQueryIdPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof evaluateQueryEvaluationQueryQueryIdPost>>, TError,{queryId: string;data: EvaluateRequest | null}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof evaluateQueryEvaluationQueryQueryIdPost>>,
        TError,
        {queryId: string;data: EvaluateRequest | null},
        TContext
      > => {
      return useMutation(getEvaluateQueryEvaluationQueryQueryIdPostMutationOptions(options), queryClient);
    }
    